# Generated by Django 3.0.7 on 2020-06-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='orderId',
        ),
    ]
